from __future__ import annotations

from typing import Any, Protocol


class PlatformAdapter(Protocol):
    async def search(self, query: str, limit: int) -> list[dict[str, Any]]: ...
    async def open_content(self, url: str) -> None: ...
    async def extract_content(self) -> dict[str, Any]: ...
    async def download_media(self, content: dict[str, Any]) -> list[bytes]: ...
    async def close(self) -> None: ...
