from __future__ import annotations

from typing import Any, Protocol


class BrowserAdapter(Protocol):
    async def open(self, url: str) -> None: ...
    async def scroll(self, amount: int) -> None: ...
    async def extract_visible_content(
        self, item_selector: str | None = None, field_selectors: dict[str, str] | None = None,
    ) -> list[dict[str, Any]]: ...
    async def screenshot(self) -> bytes: ...
    async def download_media(self, url: str) -> bytes: ...
    async def is_access_blocked(self, indicators: list[str]) -> bool: ...
    async def close(self) -> None: ...
